export const speakers = [
  {
    name: 'Jakub Andrzejewski',
    country: 'POL',
    github: 'Baroshem',
    bg: 'bg-vue',
  },
  {
    name: 'Adam Berecz',
    country: 'HUN',
    github: 'adamberecz',
    bg: 'bg-vue-light',
  },
  {
    name: 'Konstantin Bifert',
    country: 'NED',
    github: 'kissu',
    bg: 'bg-vue',
  },
  {
    name: 'Louëlla Creemers',
    country: 'NED',
    github: 'LouellaCreemers',
    bg: 'bg-vue-light',
  },
  {
    name: 'Julien Huang',
    country: 'FRA',
    github: 'huang-julien',
    bg: 'bg-vue',
  },
  {
    name: 'Alexander Lichter',
    country: 'NED',
    github: 'TheAlexLichter',
    bg: 'bg-vue-light',
  },
  {
    name: 'Juan Andrés Núñez',
    country: 'ESP',
    github: 'juanwmedia',
    bg: 'bg-vue',
  },
  {
    name: 'Alexander Opalic',
    country: 'GER',
    github: 'alexanderop',
    bg: 'bg-vue-light',
  },
  {
    name: 'Alvaro Saburido Rodriguez',
    country: 'ESP',
    github: 'alvarosabu',
    bg: 'bg-vue',
  },
  {
    name: 'Alois Sečkár',
    country: 'CZE',
    github: 'AloisSeckar',
    bg: 'bg-vue-light',
  },
  {
    name: 'Thorsten Seyschab',
    country: 'GER',
    github: 'toddeTV',
    bg: 'bg-vue',
  },
  {
    name: 'Raí Siqueira',
    country: 'BRA',
    github: 'raisiqueira',
    bg: 'bg-vue-light',
  },
  {
    name: 'Anastasiia Zvenigorodskaia',
    country: 'ESP',
    github: 'zvenigorodskaia',
    bg: 'bg-vue',
  },
]
