export const sponsors = [
  {
    tier: 1,
    to: 'https://www.evidencz.com/',
    image: 'atos',
    title: 'Atos Czech Republic',
    alt: 'Atos logo',
  },
  {
    tier: 1,
    to: 'https://www.evidencz.com/',
    image: 'eviden',
    title: 'Eviden Czech Republic',
    alt: 'Eviden logo',
  },
  {
    tier: 1,
    to: 'https://www.exponet.cz/',
    image: 'exponet',
    title: 'Exponet - Your Event Manager',
    alt: 'Exponet logo',
  },
  {
    tier: 2,
    to: 'https://slideslive.com/',
    image: 'slideslive',
    title: 'SlidesLive - Professional Conference Recording',
    alt: 'SlidesLive logo',
  },
  {
    tier: 2,
    to: 'https://go.frontendnation.com/prg',
    image: 'fn',
    title: 'Frontend Nation',
    alt: 'Frontend Nation logo',
  },
  {
    tier: 2,
    to: 'https://madvue.es/',
    image: 'madvue',
    title: 'MadVue - The Vue.js Event in Madrid',
    alt: 'MadVue logo',
  },
  {
    tier: 2,
    to: 'https://www.vintasoftware.com/',
    image: 'vinta',
    title: 'Vinta Software',
    alt: 'Vinta Software logo',
  },
]
